### ISSUE TITLE
Feature: User can search for sprays

### ISSUE THREAD

**Issue by jooliecodes** [julieluangpraxay/valorant-collections#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?
Search skins within the API.

Users can type into the search bar and it will show all matching keywords. 

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.
![Desktop Home Page](https://github.com/julieluangpraxay/valorant-collections/assets/130415142/b64e9a55-6f46-48df-bbc2-fbd5999217db)

![Search Functionality Desktop](https://github.com/julieluangpraxay/valorant-collections/assets/130415142/58464208-a651-4f59-bbf0-d9d4fd853753)

![Home Page](https://github.com/julieluangpraxay/valorant-collections/assets/130415142/d0a801d0-40fe-4d03-839d-d0ca4f528f90)

![Hamburger Menu Side Bar](https://github.com/julieluangpraxay/valorant-collections/assets/130415142/b0ec7b17-cc8c-4930-b43a-c831184ba658)

![Group 17](https://github.com/julieluangpraxay/valorant-collections/assets/130415142/5be2479f-7f83-4374-b812-112f0e526eb3)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Create html header, including logo.
- [x] Add image carousel of valorant banners.
- [x] Create the search bar, add the placeholder text, and style all elements according to the figma, add a magnifying class at the start of the search bar. 
- [x] Add the nav bar and style in CSS.
- [x] Write the javascript to make a request to the API.
- [x] Loop through the data to include all sprays that are not null.
- [x] Make sure if the spray has a GIF, to show that instead of the static image.
- [x] Create a mock list for the spray image cards.
- [x] Create a dom tree of the spray cards and append elements accordingly.
- [x] Update any CSS styling after the information is created in the DOM.
- [x] Add the search functionality in JavaScript and test out the search function.
- [x] Add the bottom nav bar view swapping to the home button for now which will refresh the page and begin at the start of the home page.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
