### ISSUE TITLE
Feature: User can favorite sprays

### ISSUE THREAD

**Issue by jooliecodes** [julieluangpraxay/valorant-collections#3]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can click the heart icon to add to a favorites list.
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.
The heart will turn into a solid heart once clicked and add to the user's favorites list. 

## 🖼️ Wireframes
![Favorited heart](https://github.com/julieluangpraxay/valorant-collections/assets/130415142/05ba71c7-f051-4e94-bcbf-900c6fbfda94)
![Favorites Functionality](https://github.com/julieluangpraxay/valorant-collections/assets/130415142/e4aba1fd-3464-4b1b-b462-1a220e9d0fc5)

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] ... 
- [x] Add a font awesome heart inside of the spray card on top of the image.
- [x] Position absolute to the top right.
- [x] Add an event listener to turn the clicked heart to turn into a solid heart.
- [x] Add the targeted spray card/favorite to a favorites list in the data object.
- [x] Add local storage in the data.js file to save the favorited sprays in the data object.
- [x] Make sure the solid hearts stay solid if clicked on in the local storage.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
