### ISSUE TITLE
Feature: User can view favorites

### ISSUE THREAD

**Issue by jooliecodes** [julieluangpraxay/valorant-collections#4]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

## 📐 Functionality
Users will be able to see a new page of all their favorite sprays they favorited. 

> ##### A description of how the application will work from the perspective of the user.
Users will be able to click on the nav section of the "favorites" button to view all the sprays they favorited.

## 🖼️ Wireframes
![View Favorites (1)](https://github.com/julieluangpraxay/valorant-collections/assets/130415142/0ddc9e7e-830d-448b-bc1d-a87865b06455)
![View Favorites](https://github.com/julieluangpraxay/valorant-collections/assets/130415142/c6ba3715-bc17-447d-9a83-88ccaba596ff)
![No Favorites (1)](https://github.com/julieluangpraxay/valorant-collections/assets/130415142/e0323b6e-310e-4d28-9286-525ceabbfb3b)
![No Favorites](https://github.com/julieluangpraxay/valorant-collections/assets/130415142/8f3fca3e-af3e-400d-b62c-8ab3ce02fb48)

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Create a data view in the html for the main sprays page
- [x] Create a data view in the html for the favorites page
- [ ]  Define a function named renderSprays with a single parameter named sprays. This parameter represents a single object for a single spray from the data.favorites array. The function should generate and return a DOM tree for a single spray.
- [ ] Create an event listener on the document which listens for the DOMContentLoaded event. In the callback function for that event, loop through the data.favorites array and generate a DOM tree for each spray in the array, and append that DOM tree to the unordered list.
- [ ] Make an event listener for the favorites nav button and create a view swap function to view the favorites page or to view the main spray page.
- [ ] Hide the main spray page when the favorite button is clicked 
- [ ] Show the favorites page and create a "no favorites" text function called toggleNoFavorites which toggles the no favorites text to show or hide when the function is called and data.favorites array is null.
- [ ] Update the DOMContentLoaded to viewSwap to show the view that was displayed prior to the page refresh.
- [ ] A condition that uses toggleNoFavorites to show or to remove the no  favorites text.
- [ ] Make sure that click targets are either `<a>` or `<button>` elements.
- [ ] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.

- **Clean Up**
  - [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [ ] Remove all console logs.
  - [ ] Remove all commented out code.
  - [ ] Remove all CSS properties that have no effect.
  - [ ] Check all code for proper formatting and indentation.
  - [ ] Confirm that there are no errors in the console while using the application.
  - [ ] Confirm that all previous functionality still works without errors.
  - [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
