### ISSUE TITLE
Feature: User can delete favorited sprays

### ISSUE THREAD

**Issue by jooliecodes** [julieluangpraxay/valorant-collections#5]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?
The user can remove a favorited spray from the favorites page/list.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.
The user can click on the minus heart icon to remove it from the favorites page. 

## 🖼️ Wireframes
![Delete Favorited (1)](https://github.com/julieluangpraxay/valorant-collections/assets/130415142/90f2c052-cc75-4262-a778-2c111c10be3a)
![Delete Favorited](https://github.com/julieluangpraxay/valorant-collections/assets/130415142/74bea7a9-14eb-473e-acb2-10a4f5fc3933)

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [ ] Add the delete heart icon to the dom tree and append it on the api and search functions.
- [ ] Append the delete heart accordingly and update the css to match the Figma.
- [ ] Add an event listener for the delete heart button that removes the specific spray from the data.favorites array. 
- [ ] Check to see if the function successfully removes the spray from the favorites page and array. 
- [ ] Update all css and finalize design.

- [ ] Make sure that click targets are either `<a>` or `<button>` elements.
- [ ] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [ ] Remove all console logs.
  - [ ] Remove all commented out code.
  - [ ] Remove all CSS properties that have no effect.
  - [ ] Check all code for proper formatting and indentation.
  - [ ] Confirm that there are no errors in the console while using the application.
  - [ ] Confirm that all previous functionality still works without errors.
  - [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
